CREATE TABLE IF NOT EXISTS contractor_work_plans (
    id INT AUTO_INCREMENT PRIMARY KEY,
    vendor_name VARCHAR(150) NOT NULL,
    vendor_pic_name VARCHAR(150) NOT NULL,
    vendor_pic_phone VARCHAR(50) NULL,
    worker_count INT NOT NULL DEFAULT 0,
    internal_pic_name VARCHAR(150) NOT NULL,
    department_area VARCHAR(120) NOT NULL,
    work_title VARCHAR(200) NOT NULL,
    work_description TEXT NULL,
    work_area VARCHAR(120) NOT NULL,
    work_location VARCHAR(200) NULL,
    asset_id INT NULL,
    additional_notes TEXT NULL,
    start_at DATETIME NOT NULL,
    end_at DATETIME NOT NULL,
    estimated_duration_minutes INT NOT NULL DEFAULT 0,
    status VARCHAR(40) NOT NULL DEFAULT 'PLANNED',
    permit_document_status VARCHAR(40) NOT NULL DEFAULT 'NOT_UPLOADED',
    working_at_height TINYINT(1) NOT NULL DEFAULT 0,
    hot_work TINYINT(1) NOT NULL DEFAULT 0,
    welding TINYINT(1) NOT NULL DEFAULT 0,
    electrical_work TINYINT(1) NOT NULL DEFAULT 0,
    confined_space TINYINT(1) NOT NULL DEFAULT 0,
    heavy_equipment_activity TINYINT(1) NOT NULL DEFAULT 0,
    chemical_handling TINYINT(1) NOT NULL DEFAULT 0,
    shutdown_activity TINYINT(1) NOT NULL DEFAULT 0,
    loto_required TINYINT(1) NOT NULL DEFAULT 0,
    need_safety_standby TINYINT(1) NOT NULL DEFAULT 0,
    created_by VARCHAR(150) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by VARCHAR(150) NULL,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    permit_uploaded_by VARCHAR(150) NULL,
    permit_uploaded_at DATETIME NULL,
    work_order_id INT NULL,
    KEY ix_contractor_work_plans_vendor_name (vendor_name),
    KEY ix_contractor_work_plans_work_area (work_area),
    KEY ix_contractor_work_plans_status (status),
    KEY ix_contractor_work_plans_start_at (start_at),
    KEY ix_contractor_work_plans_asset_id (asset_id),
    KEY ix_contractor_work_plans_work_order_id (work_order_id),
    CONSTRAINT fk_contractor_work_plans_assets FOREIGN KEY (asset_id) REFERENCES assets(id) ON DELETE SET NULL,
    CONSTRAINT fk_contractor_work_plans_work_orders FOREIGN KEY (work_order_id) REFERENCES work_orders(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS contractor_work_documents (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contractor_work_plan_id INT NOT NULL,
    document_type VARCHAR(40) NOT NULL,
    document_status VARCHAR(40) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120) NOT NULL,
    size_bytes BIGINT NOT NULL DEFAULT 0,
    file_data LONGBLOB NOT NULL,
    uploaded_by VARCHAR(150) NULL,
    uploaded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NULL,
    notes TEXT NULL,
    KEY ix_contractor_work_documents_plan_id (contractor_work_plan_id),
    KEY ix_contractor_work_documents_type (document_type),
    CONSTRAINT fk_contractor_work_documents_plans FOREIGN KEY (contractor_work_plan_id) REFERENCES contractor_work_plans(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contractor_work_audits (
    id INT AUTO_INCREMENT PRIMARY KEY,
    contractor_work_plan_id INT NOT NULL,
    action VARCHAR(80) NOT NULL,
    field_name VARCHAR(120) NULL,
    old_value TEXT NULL,
    new_value TEXT NULL,
    performed_by VARCHAR(150) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY ix_contractor_work_audits_plan_id (contractor_work_plan_id),
    KEY ix_contractor_work_audits_created_at (created_at),
    CONSTRAINT fk_contractor_work_audits_plans FOREIGN KEY (contractor_work_plan_id) REFERENCES contractor_work_plans(id) ON DELETE CASCADE
);
